name: Daily IV Collection

on:
  schedule:
    # Runs at 6:30 PM ET on weekdays
    - cron: '30 22 * * 1-5'
  workflow_dispatch:

jobs:
  collect-iv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        fetch-depth: 0  # Get full history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Run daily IV collector
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python scripts/daily_iv_collector.py
    
    - name: Check if database changed
      id: check_changes
      run: |
        if git diff --quiet historical_iv.db; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "📊 Daily IV update - ${{ github.run_number }}"
        file_pattern: historical_iv.db
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com