name: Intraday IV Collection

on:
  schedule:
    # Runs every 30 minutes from 9:00 AM to 3:30 PM ET on weekdays
    # Using UTC times (13:00-19:30 UTC for EDT, 14:00-20:30 UTC for EST)
    # This covers 9:00 AM - 3:30 PM ET during EDT (summer)
    - cron: '0,30 13-19 * * 1-5'
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-intraday-iv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_OUTPUT
    
    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Run intraday IV collector
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python scripts/cron/collect_iv_intraday.py
    
    - name: Commit and push database changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update intraday IV data - ${{ steps.date.outputs.date }}"
        file_pattern: historical_iv.db
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: intraday-iv-logs-${{ github.run_number }}
        path: logs/intraday_iv_collector.log
        retention-days: 7