name: Weekly IV Maintenance

on:
  schedule:
    # Runs on Sundays at 10:00 AM and 11:00 AM ET
    # 10:00 AM ET = 14:00 UTC (EDT) / 15:00 UTC (EST)
    # 11:00 AM ET = 15:00 UTC (EDT) / 16:00 UTC (EST)
    - cron: '0 14 * * 0'  # Backfill missing data
    - cron: '0 15 * * 0'  # Recalculate IV ranks
  workflow_dispatch: # Allows manual triggering
    inputs:
      task:
        description: 'Which task to run'
        required: true
        default: 'both'
        type: choice
        options:
        - backfill
        - recalculate
        - both

jobs:
  backfill-missing-data:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 14 * * 0' || github.event.inputs.task == 'backfill' || github.event.inputs.task == 'both'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run backfill script
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python scripts/backfill_missing_iv_data.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backfill-logs
        path: logs/backfill_iv.log
        retention-days: 30

  recalculate-iv-ranks:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 15 * * 0' || github.event.inputs.task == 'recalculate' || github.event.inputs.task == 'both'
    needs: [backfill-missing-data]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run IV rank recalculation
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        python scripts/fix_iv_rank_calculations.py
    
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: recalc-logs
        path: logs/iv_rank_recalc.log
        retention-days: 30